### ISSUE TITLE
Become a collaborator on this repo

### ISSUE THREAD

**Issue by IKamyshew** [IKamyshew/mentoring-sandbox#1]
1) Create an account on github.com if you don't have one yet
2) Post your nickname or email address here so I can add you as a collaborator
3) Wait for the invite
4) Accept invite within 7 days
5) Download git extensions from https://gitextensions.github.io/
Documentation that will help: https://git-extensions-documentation.readthedocs.io/
6) Clone repository to local computer:
6.1) Click 'clone repository'
6.2) Fill the form: 
Repository to clone: https://github.com/IKamyshew/mentoring-sandbox
Destination: path/to/folder/where/you/want/to/keep/code/for/this/project
Subdirectory to create: mentoring-sandbox
Click clone
7) You should see a page that looks like on a screenshot. You can navigate to your destination path from step 6.2 to find folder with 3 files: .gitignore, delete_me.txt, .git (.git is a hidden file so may be not displayed if on your PC hidden files are not visible)

![image](https://user-images.githubusercontent.com/7879421/200625401-f1c923a3-ad0b-4928-9c77-af264600496b.png)

![image](https://user-images.githubusercontent.com/7879421/200625488-51f7657d-69dd-47d9-b1fe-967a265228ad.png)

**Comment by RomaPustyrev** [comment]
nickname on git -  RomaPustyrev

**Comment by IKamyshew** [comment]
Added to collaborators
